module.exports = {
  apps: [{
    name: 'torrentio-web',
    script: 'server.js',
    instances: 'max',
    exec_mode: 'cluster',
    env: {
      NODE_ENV: 'development',
      PORT: 3000,
      WORKERS: 4,
      LOG_LEVEL: 'info',
      REDIS_URL: 'redis://localhost:6379'
    },
    env_production: {
      NODE_ENV: 'production',
      PORT: 3000,
      WORKERS: 8,
      LOG_LEVEL: 'warn',
      REDIS_URL: 'redis://localhost:6379'
    },
    error_file: './logs/pm2-error.log',
    out_file: './logs/pm2-out.log',
    log_file: './logs/pm2-combined.log',
    time: true,
    max_memory_restart: '1G',
    node_args: '--max-old-space-size=1024',
    watch: false,
    ignore_watch: ['node_modules', 'logs', 'data'],
    merge_logs: true,
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    autorestart: true,
    max_restarts: 10,
    min_uptime: '10s',
    kill_timeout: 5000,
    listen_timeout: 3000,
    shutdown_with_message: true,
    wait_ready: true,
    kill_exit_codes: [0],
    restart_delay: 4000,
    exp_backoff_restart_delay: 100,
    source_map_support: false,
    disable_source_map_support: true,
    increment_var: 'PORT',
    instance_var: 'INSTANCE_ID',
    pid_file: './pids/app.pid',
    write_file: './pids/app.pid',
    pmx: true,
    pm2_graceful_timeout: 3000,
    pm2_kill_timeout: 5000,
    pm2_restart_delay: 4000,
    pm2_max_restarts: 10,
    pm2_min_uptime: '10s',
    pm2_max_memory_restart: '1G',
    pm2_node_args: '--max-old-space-size=1024',
    pm2_watch: false,
    pm2_ignore_watch: ['node_modules', 'logs', 'data'],
    pm2_merge_logs: true,
    pm2_log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    pm2_autorestart: true,
    pm2_kill_timeout: 5000,
    pm2_listen_timeout: 3000,
    pm2_shutdown_with_message: true,
    pm2_wait_ready: true,
    pm2_kill_exit_codes: [0],
    pm2_restart_delay: 4000,
    pm2_exp_backoff_restart_delay: 100,
    pm2_source_map_support: false,
    pm2_disable_source_map_support: true,
    pm2_increment_var: 'PORT',
    pm2_instance_var: 'INSTANCE_ID',
    pm2_pid_file: './pids/app.pid',
    pm2_write_file: './pids/app.pid',
    pm2_pmx: true
  }],
  
  deploy: {
    production: {
      user: 'node',
      host: 'localhost',
      ref: 'origin/main',
      repo: 'git@github.com:user/torrentio-web.git',
      path: '/var/www/torrentio-web',
      'pre-deploy-local': '',
      'post-deploy': 'npm install && pm2 reload ecosystem.config.js --env production',
      'pre-setup': ''
    }
  }
}; 